export const FETCH_PRODUCTS_REQUEST =
  "FETCH_PRODUCTS_REQUEST";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const ERROR = "ERROR";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
